/**
 * @file
 * @author Benjamin Golba <benjii.g@gmail.com>
 * @author Victor Lundberg <lundberg.victor@gmail.com>
 * @version 1.0
 * Copyright (©) A-Team.
 *
 * @section LICENSE
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details at
 * http://www.gnu.org/copyleft/gpl.html
 */

#include "Vertex.h"

using namespace gfx;

D3D10_INPUT_ELEMENT_DESC *VertexTransform::pInputDesc = NULL;
D3D10_INPUT_ELEMENT_DESC *VertexTransformInstance::pInputDesc = NULL;
D3D10_INPUT_ELEMENT_DESC *VertexAnimation::pInputDesc = NULL;
D3D10_INPUT_ELEMENT_DESC *VertexAnimationInstance::pInputDesc = NULL;
D3D10_INPUT_ELEMENT_DESC *VertexMultiTexture::pInputDesc = NULL;
D3D10_INPUT_ELEMENT_DESC *VertexMultiTextureInstance::pInputDesc = NULL;
D3D10_INPUT_ELEMENT_DESC *VertexGUI::pInputDesc = NULL;
D3D10_INPUT_ELEMENT_DESC *VertexGUIInstance::pInputDesc = NULL;
D3D10_INPUT_ELEMENT_DESC *VertexParticles::pInputDesc = NULL;

void gfx::InitVertexStructures()
{
	//VertexTransform
	D3D10_INPUT_ELEMENT_DESC vertexTransform[] =
	{
		{"POSITION", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"NORMAL", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TANGENT", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"UV", 0, DXGI_FORMAT_R16G16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"DIFFUSE", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"SPECULAR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"ARRAYID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TEXID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"COLOR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0}
	};

	VertexTransform::pInputDesc = myNew D3D10_INPUT_ELEMENT_DESC[VertexTransform::NUM_ELEMENTS];
	for(unsigned int i = 0; i < VertexTransform::NUM_ELEMENTS; ++i)
	{
		VertexTransform::pInputDesc[i] = vertexTransform[i];
	}

	//VertexTransformInstance
	D3D10_INPUT_ELEMENT_DESC vertexTransformInstance[] =
	{
		{"POSITION", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"NORMAL", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TANGENT", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"UV", 0, DXGI_FORMAT_R16G16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"DIFFUSE", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"SPECULAR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"ARRAYID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TEXID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"COLOR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1}
	};

	VertexTransformInstance::pInputDesc = myNew D3D10_INPUT_ELEMENT_DESC[VertexTransformInstance::NUM_ELEMENTS];
	for(unsigned int i = 0; i < VertexTransformInstance::NUM_ELEMENTS; ++i)
	{
		VertexTransformInstance::pInputDesc[i] = vertexTransformInstance[i];
	}

	//VertexAnimation
	D3D10_INPUT_ELEMENT_DESC vertexAnimation[] =
	{
		{"POSITION", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"NORMAL", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TANGENT", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"UV", 0, DXGI_FORMAT_R16G16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"DIFFUSE", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"SPECULAR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"JOINTS", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"WEIGHTS", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"ARRAYID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TEXID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"COLOR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"AINFO", 0, DXGI_FORMAT_R16G16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0}
	};

	VertexAnimation::pInputDesc = myNew D3D10_INPUT_ELEMENT_DESC[VertexAnimation::NUM_ELEMENTS];
	for(unsigned int i = 0; i < VertexAnimation::NUM_ELEMENTS; ++i)
	{
		VertexAnimation::pInputDesc[i] = vertexAnimation[i];
	}

	//VertexAnimationInstance
	D3D10_INPUT_ELEMENT_DESC vertexAnimationInstance[] =
	{
		{"POSITION", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"NORMAL", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TANGENT", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"UV", 0, DXGI_FORMAT_R16G16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"DIFFUSE", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"SPECULAR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"JOINTS", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"WEIGHTS", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"ARRAYID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TEXID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"COLOR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"AINFO", 0, DXGI_FORMAT_R16G16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1}
	};

	VertexAnimationInstance::pInputDesc = myNew D3D10_INPUT_ELEMENT_DESC[VertexAnimationInstance::NUM_ELEMENTS];
	for(unsigned int i = 0; i < VertexAnimationInstance::NUM_ELEMENTS; ++i)
	{
		VertexAnimationInstance::pInputDesc[i] = vertexAnimationInstance[i];
	}

	//VertexMultiTexture.
	D3D10_INPUT_ELEMENT_DESC vertexMultiTexture[] =
	{
		{"POSITION", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"NORMAL", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TANGENT", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"UV", 0, DXGI_FORMAT_R16G16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"DIFFUSE", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"SPECULAR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"ARRAYSLICE", 0, DXGI_FORMAT_R32_UINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"ARRAYID", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TEXID", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"COLOR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0}
	};

	VertexMultiTexture::pInputDesc = myNew D3D10_INPUT_ELEMENT_DESC[VertexMultiTexture::NUM_ELEMENTS];
	for(unsigned int i = 0; i < VertexMultiTexture::NUM_ELEMENTS; ++i)
	{
		VertexMultiTexture::pInputDesc[i] = vertexMultiTexture[i];
	}

	//VertexMultiTextureInstance
	D3D10_INPUT_ELEMENT_DESC vertexMultiTextureInstance[] =
	{
		{"POSITION", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"NORMAL", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TANGENT", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"UV", 0, DXGI_FORMAT_R16G16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"DIFFUSE", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"SPECULAR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"ARRAYSLICE", 0, DXGI_FORMAT_R32_UINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"ARRAYID", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TEXID", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"COLOR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1}
	};

	VertexMultiTextureInstance::pInputDesc = myNew D3D10_INPUT_ELEMENT_DESC[VertexMultiTextureInstance::NUM_ELEMENTS];
	for(unsigned int i = 0; i < VertexMultiTextureInstance::NUM_ELEMENTS; ++i)
	{
		VertexMultiTextureInstance::pInputDesc[i] = vertexMultiTextureInstance[i];
	}

	D3D10_INPUT_ELEMENT_DESC vertexParticles[] =
	{
		{"POSITION",	0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"VELOCITY",	0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"SIZE",		0, DXGI_FORMAT_R32G32_FLOAT,		0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"AGE",			0, DXGI_FORMAT_R32_FLOAT,			0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TYPE",		0, DXGI_FORMAT_R32_SINT,			0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"ID",			0, DXGI_FORMAT_R32_SINT,			0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0}
	};

	VertexParticles::pInputDesc = myNew D3D10_INPUT_ELEMENT_DESC[VertexParticles::NUM_ELEMENTS];
	for(unsigned int i = 0; i < VertexParticles::NUM_ELEMENTS; ++i)
	{
		VertexParticles::pInputDesc[i] = vertexParticles[i];
	}

	//VertexGUI
	D3D10_INPUT_ELEMENT_DESC vertexGUI[] =
	{
		{"POSITION", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"UV", 0, DXGI_FORMAT_R16G16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"COLOR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"ARRAYID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TEXID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"TRANSFORM", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0}
	};

	VertexGUI::pInputDesc = myNew D3D10_INPUT_ELEMENT_DESC[VertexGUI::NUM_ELEMENTS];
	for(unsigned int i = 0; i < VertexGUI::NUM_ELEMENTS; ++i)
	{
		VertexGUI::pInputDesc[i] = vertexGUI[i];
	}

	//VertexGUIInstance
	D3D10_INPUT_ELEMENT_DESC vertexGUIInstance[] =
	{
		{"POSITION", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"UV", 0, DXGI_FORMAT_R16G16_FLOAT, 0, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_VERTEX_DATA, 0},
		{"COLOR", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"ARRAYID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TEXID", 0, DXGI_FORMAT_R32_SINT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 1, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 2, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1},
		{"TRANSFORM", 3, DXGI_FORMAT_R32G32B32A32_FLOAT, 1, D3D10_APPEND_ALIGNED_ELEMENT, D3D10_INPUT_PER_INSTANCE_DATA, 1}
	};

	VertexGUIInstance::pInputDesc = myNew D3D10_INPUT_ELEMENT_DESC[VertexGUIInstance::NUM_ELEMENTS];
	for(unsigned int i = 0; i < VertexGUIInstance::NUM_ELEMENTS; ++i)
	{
		VertexGUIInstance::pInputDesc[i] = vertexGUIInstance[i];
	}
}

void gfx::DestroyVertexStructures()
{
	if(VertexTransform::pInputDesc)
	{
		delete [] VertexTransform::pInputDesc;
		VertexTransform::pInputDesc = NULL;
	}
	if(VertexTransformInstance::pInputDesc)
	{
		delete [] VertexTransformInstance::pInputDesc;
		VertexTransformInstance::pInputDesc = NULL;
	}
	if(VertexAnimation::pInputDesc)
	{
		delete [] VertexAnimation::pInputDesc;
		VertexAnimation::pInputDesc = NULL;
	}
	if(VertexAnimationInstance::pInputDesc)
	{
		delete [] VertexAnimationInstance::pInputDesc;
		VertexAnimationInstance::pInputDesc = NULL;
	}
	if(VertexMultiTexture::pInputDesc)
	{
		delete [] VertexMultiTexture::pInputDesc;
		VertexMultiTexture::pInputDesc = NULL;
	}
	if(VertexMultiTextureInstance::pInputDesc)
	{
		delete [] VertexMultiTextureInstance::pInputDesc;
		VertexMultiTextureInstance::pInputDesc = NULL;
	}
	if(VertexParticles::pInputDesc)
	{
		delete [] VertexParticles::pInputDesc;
		VertexParticles::pInputDesc = NULL;
	}
	if(VertexGUI::pInputDesc)
	{
		delete [] VertexGUI::pInputDesc;
		VertexGUI::pInputDesc = NULL;
	}
	if(VertexGUIInstance::pInputDesc)
	{
		delete [] VertexGUIInstance::pInputDesc;
		VertexGUIInstance::pInputDesc = NULL;
	}
}